"""New setup function implementation - will be integrated into cli.py"""

def setup_new_implementation():
    """
    Modern setup that creates profile YAML files instead of .env

    Creates:
    - .llm_providers.yaml
    - .mcp_services.yaml
    - ~/.testmcpy (API keys only)
    """
    import os
    from pathlib import Path
    import yaml
    from rich.console import Console
    from rich.panel import Panel

    console = Console()

    console.print(
        Panel.fit(
            "[bold cyan]testmcpy Interactive Setup[/bold cyan]\n"
            "[dim]Create profile configuration files for LLM providers and MCP servers[/dim]",
            border_style="cyan",
        )
    )

    # Detect API keys from environment
    anthropic_key = os.getenv("ANTHROPIC_API_KEY", "")
    openai_key = os.getenv("OPENAI_API_KEY", "")
    ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

    # === 1. API Keys Setup (~/.testmcpy) ===
    console.print("\n[bold]Step 1: API Keys Configuration[/bold]")
    console.print("[dim]API keys are stored separately from profiles for security[/dim]\n")

    api_key_path = Path.home() / ".testmcpy"
    api_key_lines = []

    if api_key_path.exists():
        console.print(f"[green]✓ Found existing ~/.testmcpy[/green]")
        # Read existing file to preserve other settings
        existing = api_key_path.read_text().splitlines()
        api_key_lines = [line for line in existing if not line.startswith(("ANTHROPIC_API_KEY=", "OPENAI_API_KEY=", "OLLAMA_BASE_URL="))]

    # Anthropic API Key
    if anthropic_key:
        console.print(f"[green]✓ Detected ANTHROPIC_API_KEY from environment[/green]")
        console.print(f"[dim]  Current: {anthropic_key[:12]}...{anthropic_key[-4:]}[/dim]")
        use_env = console.input("  Use this key? [Y/n]: ").strip().lower()
        if use_env not in ["n", "no"]:
            api_key_lines.append(f"ANTHROPIC_API_KEY={anthropic_key}")
        else:
            new_key = console.input("  Enter new Anthropic API key: ").strip()
            if new_key:
                api_key_lines.append(f"ANTHROPIC_API_KEY={new_key}")
    else:
        console.print("[yellow]No ANTHROPIC_API_KEY detected in environment[/yellow]")
        new_key = console.input("Enter Anthropic API key (or press Enter to skip): ").strip()
        if new_key:
            api_key_lines.append(f"ANTHROPIC_API_KEY={new_key}")

    # OpenAI API Key
    if openai_key:
        console.print(f"\n[green]✓ Detected OPENAI_API_KEY from environment[/green]")
        console.print(f"[dim]  Current: {openai_key[:12]}...{openai_key[-4:]}[/dim]")
        use_env = console.input("  Use this key? [Y/n]: ").strip().lower()
        if use_env not in ["n", "no"]:
            api_key_lines.append(f"OPENAI_API_KEY={openai_key}")
        else:
            new_key = console.input("  Enter new OpenAI API key: ").strip()
            if new_key:
                api_key_lines.append(f"OPENAI_API_KEY={new_key}")
    else:
        console.print("\n[dim]OpenAI API key (optional, press Enter to skip)[/dim]")
        new_key = console.input("Enter OpenAI API key: ").strip()
        if new_key:
            api_key_lines.append(f"OPENAI_API_KEY={new_key}")

    # Ollama URL
    console.print(f"\n[dim]Ollama base URL (for local models)[/dim]")
    new_url = console.input(f"Ollama URL [{ollama_url}]: ").strip() or ollama_url
    if new_url != "http://localhost:11434":
        api_key_lines.append(f"OLLAMA_BASE_URL={new_url}")

    # Write API keys file
    if api_key_lines:
        api_key_lines.insert(0, "# testmcpy API Keys")
        api_key_lines.insert(1, "# Generated by testmcpy setup")
        api_key_lines.insert(2, "")
        api_key_path.write_text("\n".join(api_key_lines) + "\n")
        console.print(f"\n[green]✓ API keys saved to:[/green] {api_key_path}")

    # === 2. LLM Providers Setup (.llm_providers.yaml) ===
    console.print("\n[bold]Step 2: LLM Provider Profiles[/bold]")
    console.print("[dim]Configure which LLM models to use for testing[/dim]\n")

    llm_path = Path.cwd() / ".llm_providers.yaml"
    llm_exists = llm_path.exists()

    if llm_exists and not force:
        console.print(f"[green]✓ Found existing .llm_providers.yaml[/green]")
        overwrite = console.input("Recreate? [y/N]: ").strip().lower()
        if overwrite not in ["y", "yes"]:
            console.print("[dim]Keeping existing LLM provider configuration[/dim]")
            llm_exists = False  # Skip creation

    if not llm_exists or force:
        console.print("Select default LLM provider:")
        console.print("1. [cyan]Anthropic[/cyan] - Claude models (best tool calling)")
        console.print("2. [cyan]OpenAI[/cyan] - GPT models")
        console.print("3. [cyan]Ollama[/cyan] - Local models (free)")

        provider_choice = console.input("\nChoice [1]: ").strip() or "1"

        llm_config = {
            "default": "prod",
            "profiles": {
                "prod": {
                    "name": "Production",
                    "description": "High-quality models for production use",
                    "providers": []
                }
            }
        }

        if provider_choice == "1":
            # Anthropic
            console.print("\n[bold]Select Claude model:[/bold]")
            console.print("1. [cyan]claude-sonnet-4-5[/cyan] - Latest Sonnet (recommended)")
            console.print("2. [cyan]claude-haiku-4-5[/cyan] - Fast & efficient")
            console.print("3. [cyan]claude-opus-4-1[/cyan] - Most powerful")
            model_choice = console.input("\nChoice [1]: ").strip() or "1"

            models = {
                "1": "claude-sonnet-4-5",
                "2": "claude-haiku-4-5",
                "3": "claude-opus-4-1"
            }
            model = models.get(model_choice, "claude-sonnet-4-5")

            llm_config["profiles"]["prod"]["providers"].append({
                "name": f"Claude {model.split('-')[1].title()}",
                "provider": "anthropic",
                "model": model,
                "api_key_env": "ANTHROPIC_API_KEY",
                "timeout": 60,
                "default": True
            })

        elif provider_choice == "2":
            # OpenAI
            console.print("\n[bold]Select GPT model:[/bold]")
            console.print("1. [cyan]gpt-4o[/cyan] - GPT-4 Optimized (recommended)")
            console.print("2. [cyan]gpt-4-turbo[/cyan] - GPT-4 Turbo")
            console.print("3. [cyan]gpt-3.5-turbo[/cyan] - Faster & cheaper")
            model_choice = console.input("\nChoice [1]: ").strip() or "1"

            models = {
                "1": "gpt-4o",
                "2": "gpt-4-turbo",
                "3": "gpt-3.5-turbo"
            }
            model = models.get(model_choice, "gpt-4o")

            llm_config["profiles"]["prod"]["providers"].append({
                "name": f"GPT-4 {model.split('-')[-1].title()}",
                "provider": "openai",
                "model": model,
                "api_key_env": "OPENAI_API_KEY",
                "timeout": 60,
                "default": True
            })

        else:
            # Ollama
            console.print("\n[bold]Select Ollama model:[/bold]")
            console.print("1. [cyan]llama3.1:8b[/cyan] - Llama 3.1 8B (recommended)")
            console.print("2. [cyan]llama3.1:70b[/cyan] - Llama 3.1 70B (more capable)")
            console.print("3. [cyan]qwen2.5:14b[/cyan] - Qwen 2.5 14B (strong coding)")
            model_choice = console.input("\nChoice [1]: ").strip() or "1"

            models = {
                "1": "llama3.1:8b",
                "2": "llama3.1:70b",
                "3": "qwen2.5:14b"
            }
            model = models.get(model_choice, "llama3.1:8b")

            llm_config["profiles"]["prod"]["providers"].append({
                "name": f"Ollama {model}",
                "provider": "ollama",
                "model": model,
                "base_url": ollama_url,
                "timeout": 120,
                "default": True
            })

        llm_path.write_text(yaml.dump(llm_config, sort_keys=False, default_flow_style=False))
        console.print(f"[green]✓ Created .llm_providers.yaml[/green]")

    # === 3. MCP Services Setup (.mcp_services.yaml) ===
    console.print("\n[bold]Step 3: MCP Server Profiles[/bold]")
    console.print("[dim]Configure MCP server connections[/dim]\n")

    mcp_path = Path.cwd() / ".mcp_services.yaml"
    mcp_exists = mcp_path.exists()

    if mcp_exists and not force:
        console.print(f"[green]✓ Found existing .mcp_services.yaml[/green]")
        overwrite = console.input("Recreate? [y/N]: ").strip().lower()
        if overwrite not in ["y", "yes"]:
            console.print("[dim]Keeping existing MCP configuration[/dim]")
            mcp_exists = False  # Skip creation

    if not mcp_exists or force:
        mcp_url = console.input("MCP Server URL (e.g., http://localhost:5008/mcp/): ").strip()

        if mcp_url:
            console.print("\n[bold]MCP Authentication:[/bold]")
            console.print("1. [cyan]Bearer Token[/cyan] - Static token")
            console.print("2. [cyan]No Auth[/cyan]")
            auth_choice = console.input("\nChoice [1]: ").strip() or "1"

            mcp_config = {
                "default": "local",
                "profiles": {
                    "local": {
                        "name": "Local Development",
                        "mcps": [
                            {
                                "name": "My MCP Server",
                                "mcp_url": mcp_url
                            }
                        ]
                    }
                }
            }

            if auth_choice == "1":
                token = console.input("Bearer Token: ").strip()
                if token:
                    mcp_config["profiles"]["local"]["mcps"][0]["auth"] = {
                        "type": "bearer",
                        "token": token
                    }

            mcp_path.write_text(yaml.dump(mcp_config, sort_keys=False, default_flow_style=False))
            console.print(f"[green]✓ Created .mcp_services.yaml[/green]")
        else:
            console.print("[yellow]Skipped MCP configuration - you can run setup again or copy .mcp_services.yaml.example[/yellow]")

    # === Summary ===
    console.print("\n[bold green]✓ Setup Complete![/bold green]\n")
    console.print("[bold]Next steps:[/bold]")
    console.print("1. Run: [cyan]testmcpy llm-profiles[/cyan]  # List configured LLM profiles")
    console.print("2. Run: [cyan]testmcpy profiles[/cyan]  # List configured MCP profiles")
    console.print("3. Run: [cyan]testmcpy tools[/cyan]  # List available MCP tools")
    console.print("4. Run: [cyan]testmcpy serve[/cyan]  # Start the web UI")
    console.print("\n[dim]Edit .llm_providers.yaml and .mcp_services.yaml to add more profiles[/dim]")
